"""empty message

Revision ID: 7334beca7488
Revises: 6850c5c8e7fb
Create Date: 2019-01-08 14:58:37.900991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7334beca7488'
down_revision = '6850c5c8e7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('admin_team', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'admin_team')
    # ### end Alembic commands ###
