"""empty message

Revision ID: dcd90c44806f
Revises: bbb6e76864b7
Create Date: 2019-01-16 13:47:42.633882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd90c44806f'
down_revision = 'bbb6e76864b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('repeat_number', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('repeat_times', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('repeat_type', sa.String(length=6), nullable=True))
    op.add_column('messages', sa.Column('repeatable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'repeatable')
    op.drop_column('messages', 'repeat_type')
    op.drop_column('messages', 'repeat_times')
    op.drop_column('messages', 'repeat_number')
    # ### end Alembic commands ###
