"""empty message

Revision ID: 1d5351822d50
Revises: 57fd8577e306
Create Date: 2019-01-08 09:26:35.146580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5351822d50'
down_revision = '57fd8577e306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'topic',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # op.drop_constraint('messages_title_key', 'messages', type_='unique')
    op.create_unique_constraint(None, 'messages', ['topic'])
    # op.drop_column('messages', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='unique')
    op.create_unique_constraint('messages_title_key', 'messages', ['title'])
    op.alter_column('messages', 'topic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
