"""empty message

Revision ID: 39f26e828e01
Revises: 
Create Date: 2018-12-20 10:13:57.390930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f26e828e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('admin_requested', sa.Boolean(), nullable=True))
    op.add_column('people', sa.Column('admin_requested_date', sa.DateTime(), nullable=True))
    op.add_column('people', sa.Column('admin_role_requested', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'admin_role_requested')
    op.drop_column('people', 'admin_requested_date')
    op.drop_column('people', 'admin_requested')
    # ### end Alembic commands ###
