"""empty message

Revision ID: 57fd8577e306
Revises: 673f8ea6e658
Create Date: 2019-01-02 15:20:34.706133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fd8577e306'
down_revision = '673f8ea6e658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('owner', sa.String(length=50), nullable=True, default='Mozilla'))
    op.add_column('messages', sa.Column('team', sa.String(length=50), nullable=True, default='HR'))
    op.add_column('messages', sa.Column('topic', sa.String(length=50), nullable=True, default='ALL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'topic')
    op.drop_column('messages', 'team')
    op.drop_column('messages', 'owner')
    # ### end Alembic commands ###
