"""empty message

Revision ID: 673f8ea6e658
Revises: 39f26e828e01
Create Date: 2018-12-20 16:45:56.186215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673f8ea6e658'
down_revision = '39f26e828e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('admin_request_updated_by', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('admin_status', sa.String(), nullable=True))
    op.add_column('people', sa.Column('admin_status_updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'admin_status_updated_date')
    op.drop_column('people', 'admin_status')
    op.drop_column('people', 'admin_request_updated_by')
    # ### end Alembic commands ###
