"""empty message

Revision ID: bbb6e76864b7
Revises: 7334beca7488
Create Date: 2019-01-08 15:23:55.488131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb6e76864b7'
down_revision = '7334beca7488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
